<a href="https://colab.research.google.com/github/rajlaxmiac/LogicMojo-AI-ML-April26-RajlaxmiSingh/blob/main/Panda2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
data = { 'name': ['Shweta','Avi','Bodhi'],
        'City': ['Seattle','Newyork','Seattle'],
         'Age':[43, 41, 5]}
df = pd.DataFrame(data)

df

print(df[['name', 'City']])

     name     City
0  Shweta  Seattle
1     Avi  Newyork
2   Bodhi  Seattle

In [ ]:
import pandas as pd
data = {
    'Name': ['United States', 'India', 'Canada', 'Dubai', 'China', 'Korea'],
    'Area': [5000000, 6000000, 7000000, 8000000, 3000000, 2000000],
    'Population': [3000000, 4000000, 5000000, 6000000, 7000000, 8000000]
}

df = pd.DataFrame(data)

df[(df['Population'] > 77777777) | (df['Area'] >  5000000)]

     Name     Area  Population
1   India  6000000     4000000
2  Canada  7000000     5000000
3   Dubai  8000000     6000000

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/BikeIndia.csv')

df.head()

,instant,dteday,season,yr,mnth,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed,casual,registered,cnt
0,1,01-01-2018,1,0,1,0,6,0,2,14.110847,18.18125,80.5833,10.749882,331,654,985
1,2,02-01-2018,1,0,1,0,0,0,2,14.902598,17.68695,69.6087,16.652113,131,670,801
2,3,03-01-2018,1,0,1,0,1,1,1,8.050924,9.47025,43.7273,16.636703,120,1229,1349
3,4,04-01-2018,1,0,1,0,2,1,1,8.200000,10.60610,59.0435,10.739832,108,1454,1562
4,5,05-01-2018,1,0,1,0,3,1,1,9.305237,11.46350,43.6957,12.522300,82,1518,1600

In [ ]:
df.shape

(730, 16)

In [ ]:
df[['dteday', 'cnt']]

         dteday   cnt
0    01-01-2018   985
1    02-01-2018   801
2    03-01-2018  1349
3    04-01-2018  1562
4    05-01-2018  1600
..          ...   ...
725  27-12-2019  2114
726  28-12-2019  3095
727  29-12-2019  1341
728  30-12-2019  1796
729  31-12-2019  2729

[730 rows x 2 columns]

In [ ]:


# Example 1 — Get all columns for row 0
df.loc[0]

# Example 2 — Get only date and cnt column
df.loc[0:5, ['dteday', 'cnt']]

# Example 3 — Get rows where season is Summer (3)
df.loc[df['season'] == 3, ['dteday', 'cnt']]

         dteday   cnt
171  21-06-2018  4835
172  22-06-2018  4507
173  23-06-2018  4790
174  24-06-2018  4991
175  25-06-2018  5202
..          ...   ...
625  18-09-2019  4073
626  19-09-2019  7591
627  20-09-2019  7720
628  21-09-2019  8167
629  22-09-2019  8395

[188 rows x 2 columns]

In [ ]:
df[df['cnt'] > 4000][['dteday', 'cnt']]

         dteday   cnt
110  21-04-2018  4189
112  23-04-2018  4036
113  24-04-2018  4191
114  25-04-2018  4073
115  26-04-2018  4400
..          ...   ...
713  15-12-2019  5047
715  17-12-2019  4585
716  18-12-2019  5557
717  19-12-2019  5267
718  20-12-2019  4128

[452 rows x 2 columns]

In [ ]:
# Rainy days (weathersit=3) AND still high rentals
df[(df['weathersit'] == 3) & (df['cnt'] > 1000)][['dteday','weathersit','cnt']]

         dteday  weathersit   cnt
89   31-03-2018           3  1685
248  06-09-2018           3  2710
249  07-09-2018           3  1996
250  08-09-2018           3  1842
284  12-10-2018           3  2416
291  19-10-2018           3  2424
319  16-11-2018           3  1817
324  21-11-2018           3  2765
325  22-11-2018           3  1607
339  06-12-2018           3  2594
406  11-02-2019           3  2169
476  22-04-2019           3  1027
566  21-07-2019           3  4459
639  02-10-2019           3  4639

In [ ]:
# Summer OR Fall high rental days
df[(df['season'] == 3) | (df['season'] == 4)][['dteday','season','cnt']]

         dteday  season   cnt
171  21-06-2018       3  4835
172  22-06-2018       3  4507
173  23-06-2018       3  4790
174  24-06-2018       3  4991
175  25-06-2018       3  5202
..          ...     ...   ...
714  16-12-2019       4  3786
715  17-12-2019       4  4585
716  18-12-2019       4  5557
717  19-12-2019       4  5267
718  20-12-2019       4  4128

[366 rows x 3 columns]

In [ ]:
df[['dteday','temp','cnt']].head(10)

       dteday       temp   cnt
0  01-01-2018  14.110847   985
1  02-01-2018  14.902598   801
2  03-01-2018   8.050924  1349
3  04-01-2018   8.200000  1562
4  05-01-2018   9.305237  1600
5  06-01-2018   8.378268  1606
6  07-01-2018   8.057402  1510
7  08-01-2018   6.765000   959
8  09-01-2018   5.671653   822
9  10-01-2018   6.184153  1321

In [ ]:
df[['dteday','temp','cnt']].tail(10)

         dteday       temp   cnt
720  22-12-2019  10.899153  1749
721  23-12-2019  10.079153  1787
722  24-12-2019   9.483464   920
723  25-12-2019  11.943464  1013
724  26-12-2019   9.976653   441
725  27-12-2019  10.420847  2114
726  28-12-2019  10.386653  3095
727  29-12-2019  10.386653  1341
728  30-12-2019  10.489153  1796
729  31-12-2019   8.849153  2729

In [ ]:
df.loc[(df['season'] == 3) &
       (df['cnt'] > 3000), ['dteday','season','cnt']]

         dteday  season   cnt
171  21-06-2018       3  4835
172  22-06-2018       3  4507
173  23-06-2018       3  4790
174  24-06-2018       3  4991
175  25-06-2018       3  5202
..          ...     ...   ...
625  18-09-2019       3  4073
626  19-09-2019       3  7591
627  20-09-2019       3  7720
628  21-09-2019       3  8167
629  22-09-2019       3  8395

[184 rows x 3 columns]

In [ ]:
df[df['cnt'] > 4000][['dteday','cnt']]

         dteday   cnt
110  21-04-2018  4189
112  23-04-2018  4036
113  24-04-2018  4191
114  25-04-2018  4073
115  26-04-2018  4400
..          ...   ...
713  15-12-2019  5047
715  17-12-2019  4585
716  18-12-2019  5557
717  19-12-2019  5267
718  20-12-2019  4128

[452 rows x 2 columns]

In [ ]:
df.iloc[50:61, 0:4]

    instant      dteday  season  yr
50       51  20-02-2018       1   0
51       52  21-02-2018       1   0
52       53  22-02-2018       1   0
53       54  23-02-2018       1   0
54       55  24-02-2018       1   0
55       56  25-02-2018       1   0
56       57  26-02-2018       1   0
57       58  27-02-2018       1   0
58       59  28-02-2018       1   0
59       60  01-03-2018       1   0
60       61  02-03-2018       1   0

In [ ]:
df.groupby('season')['cnt'].mean()

season
1    2608.411111
2    4992.331522
3    5644.303191
4    4728.162921
Name: cnt, dtype: float64

In [ ]:
df[(df['workingday'] == 1) &
   (df['weathersit'] == 1) &
   (df['cnt'] > 3500)][['dteday','workingday','weathersit','cnt']]

         dteday  workingday  weathersit   cnt
109  20-04-2018           1           1  3944
110  21-04-2018           1           1  4189
114  25-04-2018           1           1  4073
115  26-04-2018           1           1  4400
118  29-04-2018           1           1  4595
..          ...         ...         ...   ...
704  06-12-2019           1           1  5375
711  13-12-2019           1           1  5532
712  14-12-2019           1           1  5611
716  18-12-2019           1           1  5557
717  19-12-2019           1           1  5267

[250 rows x 4 columns]